### ISSUE TITLE
Abstract classes should have code to be parsed as well

### ISSUE THREAD

**Issue by stephanenicolas** [bluelinelabs/LoganSquare#36] opened 2015-02-24 17:45 UTC
If `class B` extends `abstract class A`, then we will need to be able to parse A properly to get B parsed. 

The only workaround for now is to remove the abstract modifier which is a bad practice.

**Comment by EricKuck** [comment] 2015-02-24 18:03
This should be how it works already. Do you have a basic example of something that doesn't work as expected?

**Comment by stephanenicolas** [comment] 2015-02-24 18:05
I don't have any gist. But if you create a model class that inherits an
abstract class, both annotation with @JsonObject, then you will see that
the code generated to parse/serialize the abstract class will not contain
anything to parse the class.



2015-02-24 10:03 GMT-08:00 Eric Kuck <notifications@github.com>:

**Comment by EricKuck** [comment] 2015-02-24 18:16
I just tested this and there is no difference in the generated code between a class with an abstract parent and one with a concrete parent. A gist of the issue is the only way I'm going to be able to reproduce it.

**Comment by EricKuck** [comment] 2015-02-24 18:18
PS - Might be interested in using your reflection-no-reflection library in this to help support parsing and serializing generics in the future. What's the status on that? It doesn't look like it's been updated for a while. Would it work well for a project like this?

**Comment by EricKuck** [comment] 2015-02-24 18:40
Update: I did end up finding the issue. While the child class's code is generated the same way, the parent's isn't getting generated correctly when abstract. Sorry about that! Will be fixed soon.

**Comment by stephanenicolas** [comment] 2015-02-24 18:42
Thx Eric. That was a bit a blocker for us to use the lib.

Reflection no Relection is not mature at all. It's quite an experimental
thing, it's close to work for fields though but it's not mature at all.
Volunteers welcome though ;)

S.

2015-02-24 10:40 GMT-08:00 Eric Kuck <notifications@github.com>:

**Comment by EricKuck** [comment] 2015-02-24 18:44
Not sure if you saw my last update (I don't think github emails out edits), but I didn't end up finding the issue after all. It's working correctly for me. Can you send a sample?

**Comment by stephanenicolas** [comment] 2015-02-24 18:45
I will do my best to retry and make a sample if that fails.Thx for
investigating it.

2015-02-24 10:44 GMT-08:00 Eric Kuck <notifications@github.com>:

**Comment by EricKuck** [comment] 2015-02-24 23:09
By any chance was the issue just that the parent (abstract) class wasn't annotated as a `@JsonObject`? Currently every class in the hierarchy that has fields that should be parsed/serialized have to be annotated.

**Comment by stephanenicolas** [comment] 2015-02-25 06:56
It was. I will try to reproduce it.

2015-02-24 15:09 GMT-08:00 Eric Kuck <notifications@github.com>:

**Comment by EricKuck** [comment] 2015-02-26 00:49
Any luck? I've run a few more tests and it always seems to work great for me. I'd like to close this if you can't reproduce.

**Comment by EricKuck** [comment] 2015-03-06 16:17
I'm gonna assume it's all working correctly and close the issue. If someone can reproduce it, I'll gladly reopen.

**Closed by EricKuck** 2015-03-06 16:17 UTC

**Comment by stephanenicolas** [comment] 2015-03-06 16:19
Hi Erik,

sorry, I had no time to retry to reproduce the issue or make a gist.

I am pretty sure I will come back to your project soon. Thanks for your
work on this, it's really a great idea and implementation.

S.

2015-03-06 8:17 GMT-08:00 Eric Kuck <notifications@github.com>:

**Comment by EricKuck** [comment] 2015-03-06 16:36
No worries at all. Just trying to keep the issues list clean.

**Comment by stephanenicolas** [comment] 2015-03-07 00:19
You do well, I love that too. And I wish I could for my own projects these
days... Snif ;)

2015-03-06 8:36 GMT-08:00 Eric Kuck <notifications@github.com>:
