### ISSUE TITLE
Caused by: java.lang.RuntimeException: JsonMapperLoaderImpl class not found. Have you included the steps needed for LoganSquare to process your annotations?

### ISSUE THREAD

**Issue by Mateuszg7** [bluelinelabs/LoganSquare#107] opened 2015-11-18 18:37 UTC
I think it might be connected with RealmList. Is it any workaround with converter or so?

**Comment by ubuntudroid** [comment] 2015-11-18 19:39
I see exactly the same error message. I sifted through the library code and in fact found no class with that name. I'm not using realm, but retrofit-logansquare if it matters.

**Comment by EricKuck** [comment] 2015-11-18 19:44
Can someone create an example project that exhibits this issue? I haven't been able to reproduce it, so I'm not sure what to do to try to fix it.

**Comment by Mateuszg7** [comment] 2015-11-18 19:49
@ubuntudroid Yes, I'm using to be precise this compile "com.github.aurae.retrofit:converter-logansquare:1.1.0, too.

**Comment by ubuntudroid** [comment] 2015-11-18 19:49
Okay, for me the issue seems to be annotation processing in kotlin files. Trying it now with POJOs.

**Comment by ubuntudroid** [comment] 2015-11-18 20:03
Yep, that was the issue. Unfortunately using [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) also didn't work so I had to revert the kotlin files to Java files. After that everything worked like a charm.

**Comment by EricKuck** [comment] 2015-11-18 20:09
@ubuntudroid Good to know! I've been planning to start using kotlin on our projects soon, so at some point soon I'll start investigating what it'll take to make it work there.

**Comment by Mateuszg7** [comment] 2015-11-18 20:10
I still have that problem.
```
@JsonObject
public class Result {
    @JsonField(name = "news")
    private RealmList<NewsStream> news;

    public RealmList<NewsStream> getNews() {
        return news;
    }

    public void setNews(RealmList<NewsStream> news) {
        this.news = news;
    }
}
```

If I change RealmList to List everything is fine

**Comment by EricKuck** [comment] 2015-11-18 20:14
Yeah, RealmList isn't supported natively. You might be able to make a TypeConverter to handle that, but the library doesn't do that automatically. Handling more collection types is something that's been on my roadmap for a while now.

**Comment by EricKuck** [comment] 2015-11-20 15:06
Sorry, there isn't really support for generic TypeConverters yet. That should be coming soon.

**Comment by eirnym** [comment] 2015-11-27 16:15
@Mateuszg7 By any way, you can make builder object from JSON data and then create your target object with collection you want. This is not the best solution as supporting anything implementing `List<T>`, but this will work.

**Comment by EricKuck** [comment] 2015-11-29 00:32
Closing this issue, as the request to be able to parse Lists to custom types is covered by #60 and #97. I'll open another issue for Kotlin support.

**Closed by EricKuck** 2015-11-29 00:32 UTC

**Comment by peterbetos** [comment] 2016-05-06 13:55
I received this error when trying this typeconverter:

`Class io.realm.UserRealmProxy could not be mapped to a JSON object. Perhaps it hasn't been annotated with @JsonObject?`

**Comment by eirnym** [comment] 2016-05-08 21:31
@peterbetos because it's proxy.

I use plain object to parse and map and then copy to realm with robust copy classes. The main reason is flexibility to protocol changes
