### ISSUE TITLE
test compatibility with java8

### ISSUE THREAD

**Issue by andaag** [bluelinelabs/LoganSquare#16] opened 2015-02-18 18:19 UTC
compiling locally with jdk8 causes test failures (see #13 ). Slightly annoying when building locally.

Test failures:
https://drive.google.com/file/d/0B_ixtCXTNKxSdlhQQ0Q5TzZiUFU/view?usp=sharing

**Comment by EricKuck** [comment] 2015-02-18 18:23
Looks like Java 8 just causes the code to be generated in a different order (but still created functionally identical classes). That's gonna be annoying to fix! Thanks for the upload, helped a lot.

**Comment by talklittle** [comment] 2015-02-18 18:34
Test failures (probably same as @andaag 's): https://gist.github.com/talklittle/11104573b03b4a8e8cb9

**Comment by EricKuck** [comment] 2015-02-18 18:40
Yep, looks the same. Not really sure how to address this, as compile-testing's built-in code generation tests basically just do a string comparison of generated vs. expected. If things are in a different order, that's gonna fail, no matter how identically they perform.

Instead of writing crazy code code that reorders other code to match what's expected, does anyone know if there's a way to force the tests to be run in Java 7 from the build.gradle?

**Comment by evant** [comment] 2015-02-19 23:30
You can check out https://github.com/google/compile-testing for comparing the actual ast instead of strings.

**Comment by EricKuck** [comment] 2015-02-20 02:05
This *should* be fixed now in commit 6fb772b249c21d1cf9498167c96f9b9b4e6dc66f. I'll close this issue for now. If there are any other JDK issues, please feel free to re-open.

**Closed by EricKuck** 2015-02-20 02:05 UTC
Labels: enhancement

**Comment by talklittle** [comment] 2015-02-20 04:54
Confirmed, seems to work fine with JDK 8. Thank you @EricKuck !
