### ISSUE TITLE
"-" symbol on jason field

### ISSUE THREAD

**Issue by miomao656** [bluelinelabs/LoganSquare#135] opened 2016-01-25 18:13 UTC
I have a json object array with field named "version-details" and i anotate it like this

@JsonField(name = "version-details")
   public List<DocumentVersionEntity> versions;

generates code like this

final List<DocumentVersionEntity> lslocalversion-details = object.versions;
    if (lslocalversion-details != null) {
      jsonGenerator.writeFieldName("version-details");
      jsonGenerator.writeStartArray();
      for (DocumentVersionEntity element1 : lslocalversion-details) {...

Naturally on compile it throws error ';' expected since we cant have object names with "-".

**Comment by qwertyfinger** [comment] 2016-02-03 07:39
yep, same problem..

**Comment by angelorohit** [comment] 2016-02-03 10:11
I'm afraid I have the same issue as well.

**Comment by miomao656** [comment] 2016-02-24 13:10
Is anybody supporting this repository at all? 
I really like this library and i want to use it for my project but this issue is just standing here for a whole month and i don't have the time to get familiar with the code to fix this. I kinda wish i do. :/

**Comment by aurae** [comment] 2016-02-25 06:51
This is a duplicate of #115, and has actually already been fixed in 35af6f9, however the change hasn't been released as a new version yet (pinging @EricKuck on this).

I have also submitted a PR related to this issue, which removes all non-alphanumeric characters from the field names generated by the annotation processor.

**Comment by miomao656** [comment] 2016-02-25 08:14
Nice tnx! :+1: I hope it will be released soon.

**Comment by EricKuck** [comment] 2016-02-29 16:26
This fix has now been pushed to jcenter. Thanks again @aurae.

**Closed by EricKuck** 2016-02-29 16:26 UTC
